name: "Deploy Project NotePad"

#test
on:
  push:
    tags:
      - "class-notepad/v*"
permissions: write-all
env:
  SOLUTION_NAME: NotePad.sln
  PROJECT_PATH: NotePad.csproj
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Istall .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
      
        #Restore the application
      - name: Restore the Application
        run: msbuild $env:SOLUTION_NAME /t:Restore /p:$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }} 
      - run: dotnet restore ${{ env.PROJECT_PATH }}
      #Create the app
      - name: Create the app
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release
      
      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -r win-x64 --self-contained -p:PublishSingleFile=true
      
      - uses: actions/create-release@v3
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
      
      - uses: csexton/release-asset-action@v3
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: bin/Release/net9.0-windows/win-x64/publish/*.exe
          release-url: ${{ steps.create_release.outputs.upload_url }}
  